---
- name: Create site
  shell: "omd create {{ item.name }}"
  ignore_errors: True
  loop: "{{ omd_sites }}"

- name: Set core
  shell: "omd config {{ item.name }} set CORE {{ item.core }}"
  loop: "{{ omd_sites }}"

- name: Set default UI
  shell: "omd config {{ item.name }} set DEFAULT_GUI {{ item.default_gui }}"
  loop: "{{ omd_sites }}"

- name: Set Thruk authorization
  shell: "omd config {{ item.name }} set THRUK_COOKIE_AUTH {{ item.thruk_cookie_auth }}"
  loop: "{{ omd_sites }}"

- name: Remove Nagios protection
  file:
    path: "/opt/omd/sites/{{ item.name }}/etc/apache/conf.d/disable_nagios.conf"
    state: absent
  loop: "{{ omd_sites }}"
  when: item.remove_nagios_protection

- name: Restart site
  shell: "omd restart {{ item.name }}"
  loop: "{{ omd_sites }}"