---
- name: Create site
  ansible.builtin.command: "omd create {{ item.name }}"
  args:
    creates: "/opt/omd/sites/{{ item.name }}/etc/omd/site.conf"
  become: true
  loop: "{{ omd_sites }}"
  notify: Configure site
