---
- name: Install Debian package
  apt:
    name: omd
  when: ansible_facts["os_family"] == "Debian"
- name: Install RedHat package
  yum:
    name: omd
  when: ansible_facts["os_family"] == "RedHat"
- name: Install SUSE package
  zypper:
    name: omd
  when: ansible_facts["os_family"] == "Suse"

- name: Enable and start service
  service:
    name: omd
    state: started
    enabled: true
  when: ansible_facts["os_family"] != "Debian"
- name: Get OMD package version
  shell: dpkg-query -f '${binary:Package}\n' -W omd-*
  register: omd_version
  when: ansible_facts["os_family"] == "Debian"
- name: Enable and start service
  service:
    name: "{{ omd_version['stdout_lines'][0] }}"
    state: started
    enabled: true
  when: ansible_facts["os_family"] == "Debian"