---
- name: Install package
  ansible.builtin.package:
    name: "{{ omd_package }}"
  become: true

- name: Enable and start service
  ansible.builtin.service:
    name: "{{ omd_service }}"
    state: started
    enabled: true
  become: true
