---
# tasks file for ansible-omd

- include: prepare.yml
  become: true
  tags: prepare

- include: install.yml
  become: true
  tags: install

- include: configure.yml
  become: true
  tags: configure