---
- include: "prepare_{{ ansible_os_family|lower }}.yml"
  become: true
  tags: prepare

- include: "install_{{ ansible_os_family|lower }}.yml"
  become: true
  tags: install

- include: configure.yml
  become: true
  tags: configure
