---
- name: Include variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - vars

- ansible.builtin.include_tasks: "prepare_{{ ansible_os_family | lower }}.yml"
  tags: prepare

- ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
        - install.yml
      paths:
        - tasks
  tags: install

- ansible.builtin.include_tasks: configure.yml
  tags: configure
