---
- name: Install requirements
  apt:
    name: "{{ omd_requisites }}"
  become: true

- name: Add GPG key
  apt_key:
    url: "{{ omd_repo_key }}"
    state: present
  become: true

- name: Add repository
  apt_repository:
    repo: "{{ omd_repo_url }}"
  become: true
