---
- name: Add GPG key
  rpm_key:
    key: "{{ omd_repo_key }}"
    state: present
  become: true

- name: Add repository
  zypper_repository:
    name: "consol-omd"
    description: "consol-omd"
    repo: "{{ omd_repo_url }}"
  # TODO: only for supported SLES versions
  become: true
