---
- name: Install requirements
  ansible.builtin.apt:
    name: "{{ omd_requisites }}"
  become: true

- name: Add GPG key
  ansible.builtin.apt_key:
    url: "{{ omd_repo_key }}"
    state: present
  become: true

- name: Add repository
  ansible.builtin.apt_repository:
    repo: "{{ omd_repo_url }}"
  become: true
