---
- name: Install requirements (Fedora)
  yum:
    name: "{{ packages_fedora }}"
  become: true
  when: ansible_facts["distribution"] == "Fedora"

- name: Add GPG key (Red Hat)
  rpm_key:
    key: "{{ key_redhat }}"
    state: present
  become: true
- name: Add EPEL GPG key
  rpm_key:
    key: "{{ key_epel }}"
    state: present
  become: true
  when: ansible_facts["distribution"] != "Fedora"


- name: Add repository (Red Hat)
  yum_repository:
    name: "consol-omd"
    description: "consol-omd"
    baseurl: "{{ repo_redhat }}"
  become: true
  when: ansible_facts["distribution"] in ["CentOS", "Red Hat Enterprise Linux"]
- name: Add EPEL repository
  yum_repository:
    name: "epel"
    description: "epel"
    baseurl: "{{ repo_epel }}"
  become: true
  when: ansible_facts["distribution"] in ["CentOS", "Red Hat Enterprise Linux"]
- name: Enable extra RHEL repositories
  rhsm_repository:
    name:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-optional-rpms
  become: true
  when: ansible_facts["distribution"] == "Red Hat Enterprise Linux" and ansible_facts["distribution_major_version"] == "7"
- name: Add repository (Fedora)
  yum_repository:
    name: "consol-omd"
    description: "consol-omd"
    baseurl: "{{ repo_fedora }}"
  become: true
  when: ansible_facts["distribution"] == "Fedora"
