---
- name: Install requirements
  ansible.builtin.yum:
    name: "{{ omd_requisites }}"
  become: true

- name: Add GPG key
  ansible.builtin.rpm_key:
    key: "{{ omd_repo_key }}"
    state: present
  become: true


- name: Add repository
  ansible.builtin.yum_repository:
    name: "consol-omd"
    description: "consol-omd"
    baseurl: "{{ omd_repo_url }}"
  become: true

- name: Enable extra RHEL repositories
  ansible.builtin.rhsm_repository:
    name:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-optional-rpms
  become: true
  when: ansible_facts["distribution"] == "Red Hat Enterprise Linux" and ansible_facts["distribution_major_version"] == "7"
