---
- name: Add Debian GPG key
  apt_key:
    url: "{{ key_debian }}"
    state: present
  when: ansible_facts["os_family"] == "Debian"
- name: Add RedHat GPG key
  rpm_key:
    url: "{{ key_redhat }}"
    state: present
  when: ansible_facts["os_family"] == "RedHat"
- name: Add EPEL GPG key
  rpm_key:
     url: "{{ key_epel }}"
     state: present
  when: ansible_facts["os_family"] == "RedHat"



- name: Add Debian repository
  apt_repository:
    url: "{{ repo_debian }}"
  when: ansible_facts["ansible_distribution"] == "Debian"
- name: Add Ubuntu repository
  apt_repository:
    url: "{{ repo_ubuntu }}"
  when: ansible_facts["ansible_distribution"] == "Ubuntu"
- name: Add RedHat repository
  yum_repository:
    baseurl: "{{ repo_redhat }}"
  when: ansible_facts["ansible_distribution"] in ["CentOS", "Red Hat Enterprise Linux"]
- name: Add EPEL repository
  yum_repository:
    baseurl: "{{ repo_epel }}"
  when: ansible_facts["ansible_distribution"] in ["CentOS", "Red Hat Enterprise Linux"]
- name: Enable extra RHEL repositories
  rhsm_repository:
    name:
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
    - rhel-7-server-optional-rpms
  when: ansible_facts["ansible_distribution"] == "Red Hat Enterprise Linux" and ansible_facts["ansible_distribution_major_version"] == "7"
- name: Add Fedora repository
  yum_repository:
    baseurl: "{{ repo_fedora }}"
  when: ansible_facts["ansible_distribution"] == "Fedora"
- name: Add SUSE repository
  zypper_repository:
    repo: "{{ repo_sles }}"
  # TODO: only for supported SLES versions
  when: ansible_facts["os_family"] == "Suse"