---
- name: Install Debian requirements
  apt:
    name: "{{ packages_debian }}"
  when: ansible_facts["os_family"] == "Debian"

- name: Add Debian GPG key
  apt_key:
    url: "{{ key_debian }}"
    state: present
  when: ansible_facts["os_family"] == "Debian"
- name: Add RedHat GPG key
  rpm_key:
    key: "{{ key_redhat }}"
    state: present
  when: ansible_facts["os_family"] == "RedHat"
- name: Add EPEL GPG key
  rpm_key:
    key: "{{ key_epel }}"
    state: present
  when: ansible_facts["os_family"] == "RedHat" and ansible_facts["distribution"] != "Fedora"


- name: Add Debian repository
  apt_repository:
    repo: "{{ repo_debian }}"
  when: ansible_facts["distribution"] == "Debian"
- name: Add Ubuntu repository
  apt_repository:
    repo: "{{ repo_ubuntu }}"
  when: ansible_facts["distribution"] == "Ubuntu"
- name: Add RedHat repository
  yum_repository:
    name: "consol-omd"
    description: "consol-omd"
    baseurl: "{{ repo_redhat }}"
  when: ansible_facts["distribution"] in ["CentOS", "Red Hat Enterprise Linux"]
- name: Add EPEL repository
  yum_repository:
    name: "epel"
    description: "epel"
    baseurl: "{{ repo_epel }}"
  when: ansible_facts["distribution"] in ["CentOS", "Red Hat Enterprise Linux"]
- name: Enable extra RHEL repositories
  rhsm_repository:
    name:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-optional-rpms
  when: ansible_facts["distribution"] == "Red Hat Enterprise Linux" and ansible_facts["distribution_major_version"] == "7"
- name: Add Fedora repository
  yum_repository:
    name: "consol-omd"
    description: "consol-omd"
    baseurl: "{{ repo_fedora }}"
  when: ansible_facts["distribution"] == "Fedora"
- name: Add SUSE repository
  zypper_repository:
    repo: "{{ repo_sles }}"
  # TODO: only for supported SLES versions
  when: ansible_facts["os_family"] == "Suse"
