---
package_omd:
  - omd-3.20-labs-edition
#  - omd-2.90-labs-edition

repo_flavor: "stable"

omd_sites:
  - name: icinga2
    core: icinga2
    default_gui: thruk
    thruk_cookie_auth: false
    remove_nagios_protection: false
