---
- name: Converge
  hosts: all
  roles:
    - role: ansible-omd
      omd_sites:
        - name: icinga2
          core: icinga2
          default_gui: thruk
          thruk_cookie_auth: false
          remove_nagios_protection: false
          admin_password: omd
