---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: centos-7
    box: centos/7
  - name: debian-buster
    box: debian/buster64
  - name: ubuntu-focal
    box: ubuntu/focal64
    memory: 1024
  - name: fedora-32
    box: fedora/32-cloud-base
    memory: 1024
provisioner:
  name: ansible
  inventory:
    host_vars:
      fedora-32:
        ansible_python_interpreter: "/usr/bin/python3"
verifier:
  name: testinfra
lint: |
    yamllint .
    ansible-lint
    flake8
