---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: centos-7
    box: centos/7
  - name: debian-buster
    box: debian/buster64
  # - name: ubuntu-eoan
  # box: ubuntu/eoan64
  # memory: 1024
  - name: fedora-30
    box: fedora/30-cloud-base
    memory: 1024
#  -name: sles-12sp2
#    box: suse/sles12sp2
provisioner:
  name: ansible
  inventory:
    host_vars:
      fedora-30:
        ansible_python_interpreter: "/usr/bin/python3"
verifier:
  name: testinfra
lint: |
    yamllint .
    ansible-lint
    flake8
