---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: centos-7
    box: generic/centos7
  - name: debian-bullseye
    box: generic/debian11
  - name: ubuntu-focal
    box: generic/ubuntu2004
    memory: 1024
  - name: fedora-36
    box: generic/fedora36
    memory: 1024
provisioner:
  name: ansible
  inventory:
    host_vars:
      fedora-36:
        ansible_python_interpreter: "/usr/bin/python3"
verifier:
  name: testinfra
lint: |
    yamllint .
    ansible-lint
    flake8
